Repository bumble-tech/bumble-doc-gen, pull requests merged in 2023-10, with the labels that each got.

#23 Removing old doc build config
  docs/README.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/shared_c.cache
  docs/tech/1.configuration/readme.md
  docs/tech/2.parser/classes/ClassEntity.md
  docs/tech/2.parser/classes/ClassEntityCollection.md
  docs/tech/2.parser/classes/ConstantEntity.md
  docs/tech/2.parser/classes/MethodEntity.md
  docs/tech/2.parser/classes/PropertyEntity.md
  docs/tech/2.parser/entity.md
  docs/tech/2.parser/entityFilterCondition.md
  docs/tech/2.parser/readme.md
  docs/tech/2.parser/sourceLocator.md
  docs/tech/3.renderer/breadcrumbs.md
  docs/tech/3.renderer/classes/BreadcrumbsHelper.md
  docs/tech/3.renderer/classes/ClassEntityCollection_2.md
  docs/tech/3.renderer/classes/GetDocumentedEntityUrl_2.md
  docs/tech/3.renderer/classes/GetDocumentedEntityUrl_3.md
  docs/tech/3.renderer/readme.md
  docs/tech/3.renderer/templates.md
  docs/tech/3.renderer/templatesDynamicBlocks.md
  docs/tech/3.renderer/templatesLinking.md
  docs/tech/3.renderer/templatesVariables.md
  docs/tech/3.renderer/twigCustomFilters.md
  docs/tech/3.renderer/twigCustomFunctions.md
  docs/tech/4.pluginSystem/readme.md
  docs/tech/classes/BaseCommand.md
  docs/tech/classes/GenerateCommand.md
  docs/tech/map.md
  docs/tech/readme.md
  selfdoc/templates/_config.yml
  selfdoc/templates/_layouts/default.html
Labels: documentation

#36 Config array
  .gitignore
  demo/demo1/demoScript.php
  demo/demo2-templates-generation/demoScript.php
  demo/demo3-add-missing-doc-blocks/demoScript.php
  demo/demo4-generating-readme-file/demoScript.php
  demo/demo5-config-array/demoScript.php
  demo/demo5-config-array/templates/README.md.twig
  docs/README.md
  docs/classes/DocGeneratorFactory.md
  docs/shared_c.cache
  docs/tech/1.configuration/readme.md
  docs/tech/2.parser/entity.md
  docs/tech/2.parser/entityFilterCondition.md
  docs/tech/2.parser/readme.md
  docs/tech/2.parser/sourceLocator.md
  docs/tech/3.renderer/breadcrumbs.md
  docs/tech/3.renderer/readme.md
  docs/tech/3.renderer/templates.md
  docs/tech/3.renderer/templatesDynamicBlocks.md
  docs/tech/3.renderer/templatesLinking.md
  docs/tech/3.renderer/templatesVariables.md
  docs/tech/3.renderer/twigCustomFilters.md
  docs/tech/3.renderer/twigCustomFunctions.md
  docs/tech/4.pluginSystem/readme.md
  docs/tech/classes/DocGeneratorFactory.md
  docs/tech/map.md
  docs/tech/readme.md
  selfdoc/templates/README.md.twig
  selfdoc/templates/tech/1.configuration/readme.md.twig
  selfdoc/templates/tech/readme.md.twig
  src/DocGeneratorFactory.php
Labels: documentation, enhancement

#41 Fix compatibility issue for PHP 8.2
  src/Core/Parser/Entity/Cache/CacheableEntityWrapperTrait.php
Labels: hacktoberfest, hacktoberfest-accepted

#45 Add Unit Tests for BumbleDocGen\Core\Configuration\ValueTransformer Namespace
  tests/Unit/Core/Configuration/ValueTransformer/ValueToClassTransformerTest.php
Labels: hacktoberfest, hacktoberfest-accepted

#47 Add Unit Tests for ValueResolver Namespace
  tests/Unit/Core/Configuration/ValueResolver/ArgvValueResolverTest.php
  tests/Unit/Core/Configuration/ValueResolver/InternalValueResolverTest.php
  tests/Unit/Core/Configuration/ValueResolver/RefValueResolverTest.php
Labels: hacktoberfest

#55 This commit will add error output
  src/Core/Logger/Handler/GenerationErrorsHandler.php
  src/Core/Renderer/RendererIteratorFactory.php
  src/DocGenerator.php
  src/di-config.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
